/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sandboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sandboxes
         * @description Get list of sandboxes
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of results */
                    limit?: number;
                    /** @description Number of results to skip */
                    offset?: number;
                    /** @description Filter by owner user ID (root users only) */
                    owner_user_id?: string;
                    /** @description Filter by project ID */
                    project_id?: string;
                    /** @description Search in sandbox names */
                    search?: string;
                    /** @description Sort by field */
                    sort_by?: string;
                    /** @description Sort order */
                    sort_order?: "asc" | "desc";
                    /** @description Filter by status */
                    status?: "created" | "starting" | "running" | "pausing" | "paused" | "resuming" | "terminating" | "terminated" | "failed";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of sandboxes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                sandboxes?: components["schemas"]["SandboxResponse"][];
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new sandbox
         * @description Create a new sandbox instance
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSandboxRequest"];
                };
            };
            responses: {
                /** @description Sandbox created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["SandboxResponse"];
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandbox_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sandbox details
         * @description Get details of a specific sandbox
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sandbox ID */
                    sandbox_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sandbox details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["SandboxResponse"];
                        };
                    };
                };
                /** @description Sandbox not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /**
         * Update sandbox
         * @description Update sandbox settings (mainly timeout)
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sandbox ID */
                    sandbox_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSandboxRequest"];
                };
            };
            responses: {
                /** @description Sandbox updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sandbox not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete sandbox
         * @description Delete a sandbox instance
         */
        delete: {
            parameters: {
                query?: {
                    /** @description Force deletion even if sandbox is running */
                    force?: boolean;
                };
                header?: never;
                path: {
                    /** @description Sandbox ID */
                    sandbox_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sandbox deletion initiated */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                note?: string;
                                sandbox_id?: string;
                                status?: string;
                            };
                            message?: string;
                        };
                    };
                };
                /** @description Sandbox not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandbox_id}/create-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create template from sandbox
         * @description Create a template from a running sandbox. The sandbox must be in running state.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sandbox ID */
                    sandbox_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTemplateFromSandboxRequest"];
                };
            };
            responses: {
                /** @description Template creation initiated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                base_template_id?: string;
                                /** Format: date-time */
                                created_at?: string;
                                custom_command?: string;
                                default_cpu_count?: number;
                                default_memory_mb?: number;
                                description?: string;
                                harbor_project?: string;
                                harbor_repository?: string;
                                harbor_tag?: string;
                                is_public?: boolean;
                                message?: string;
                                name?: string;
                                /** @description JSON string of port configurations */
                                ports?: string;
                                ready_command?: string;
                                status?: string;
                                template_id?: string;
                            };
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sandbox not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandbox_id}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deploy sandbox
         * @description Deploy a sandbox using driver-based deployment
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sandbox ID */
                    sandbox_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Target cluster ID (optional) */
                        cluster_id?: string;
                        /** @description Override CPU count (optional) */
                        cpu_count?: number;
                        /** @description Override memory in MB (optional) */
                        memory_mb?: number;
                    };
                };
            };
            responses: {
                /** @description Sandbox deployed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["SandboxDeploymentResponse"];
                            message?: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sandbox not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandbox_id}/ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sandbox ports
         * @description Get all ports (template + custom) for a sandbox
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sandbox ID */
                    sandbox_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Port list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                custom_ports?: components["schemas"]["PortConfig"][];
                                ports?: components["schemas"]["PortConfig"][];
                                template_ports?: components["schemas"]["PortConfig"][];
                            };
                        };
                    };
                };
                /** @description Sandbox not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add custom port to sandbox
         * @description Add a custom port to a running sandbox
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sandbox ID */
                    sandbox_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Port name */
                        name: string;
                        /**
                         * Format: int32
                         * @description Port number
                         */
                        port: number;
                        /**
                         * @description Port protocol
                         * @default TCP
                         * @enum {string}
                         */
                        protocol?: "TCP" | "UDP";
                        /**
                         * Format: int32
                         * @description Service port (defaults to port)
                         */
                        service_port?: number;
                    };
                };
            };
            responses: {
                /** @description Port added successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["SandboxResponse"];
                            message?: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sandbox not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandbox_id}/ports/{port}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove custom port from sandbox
         * @description Remove a custom port from a running sandbox
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Port number to remove */
                    port: number;
                    /** @description Sandbox ID */
                    sandbox_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Port removed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sandbox not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandbox_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start sandbox
         * @description Start a created sandbox
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sandbox ID */
                    sandbox_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sandbox started successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** @description Sandbox access domain */
                                domain?: string;
                            };
                            message?: string;
                        };
                    };
                };
                /** @description Bad request (e.g., sandbox already running) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sandbox not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandbox_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop sandbox
         * @description Stop a running sandbox
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sandbox ID */
                    sandbox_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sandbox stopped successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Bad request (e.g., sandbox not running) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Sandbox not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandbox_id}/terminate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Terminate sandbox
         * @description Terminate a sandbox (keeps it visible in database)
         */
        post: {
            parameters: {
                query?: {
                    /** @description Force termination */
                    force?: boolean;
                };
                header?: never;
                path: {
                    /** @description Sandbox ID */
                    sandbox_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sandbox termination initiated */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                note?: string;
                                sandbox_id?: string;
                                status?: string;
                            };
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandbox_id}/timeout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update sandbox timeout
         * @description Update the timeout for a sandbox
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Sandbox ID */
                    sandbox_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SandboxTimeoutRequest"];
                };
            };
            responses: {
                /** @description Timeout updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                remaining_time?: number;
                                timeout?: number;
                                /** Format: date-time */
                                timeout_at?: string;
                                used_lifetime?: number;
                            };
                            message?: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch delete sandboxes
         * @description Delete multiple sandboxes in a single request
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BatchDeleteRequest"];
                };
            };
            responses: {
                /** @description Batch deletion results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["BatchDeleteResponse"];
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sandbox statistics
         * @description Get sandbox statistics for the current user
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sandbox statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["SandboxStatsResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scalebox-regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available scalebox regions
         * @description Get a list of available Scalebox Regions that currently have eligible clusters.
         *     This is a public API (no authentication required) to help users discover
         *     available regions for locality-based scheduling.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of available scalebox regions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** @description List of available scalebox regions with eligible clusters */
                                scalebox_regions?: components["schemas"]["ScaleboxRegion"][];
                            };
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BatchDeleteRequest: {
            /**
             * @description Force deletion even if sandboxes are running
             * @default false
             */
            force: boolean;
            /** @description List of sandbox IDs to delete */
            sandbox_ids: string[];
        };
        BatchDeleteResponse: {
            /** @description List of failed deletions with errors */
            failed?: {
                error?: string;
                sandbox_id?: string;
            }[];
            /** @description Number of failed deletions */
            failed_count?: number;
            /** @description List of successfully deleted sandbox IDs */
            successful?: string[];
            /** @description Number of successfully deleted sandboxes */
            successful_count?: number;
        };
        CreateSandboxRequest: {
            /**
             * @description Internet access setting
             * @default true
             */
            allow_internet_access: boolean;
            /** @description Number of CPU cores */
            cpu_count?: number;
            /** @description Optional custom ports (ports not in template). Must have unique port numbers and names. */
            custom_ports?: components["schemas"]["PortConfig"][];
            /** @description Sandbox description */
            description?: string;
            /** @description Environment variables */
            env_vars?: {
                [key: string]: string;
            };
            /**
             * @description When true, return immediately; when false, wait for running/failed state
             * @default false
             */
            is_async: boolean;
            /** @description Locality preferences for sandbox scheduling (optional) */
            locality?: components["schemas"]["LocalityConfig"];
            /** @description Memory in MB */
            memory_mb?: number;
            /** @description Flexible key-value metadata */
            metadata?: {
                [key: string]: string;
            };
            /** @description Sandbox name */
            name?: string;
            /**
             * @description Network proxy country for sandbox traffic routing (optional)
             * @enum {string}
             */
            net_proxy_country?: "united-states" | "canada" | "japan" | "malaysia" | "brazil" | "france" | "italy" | "china" | "hong-kong";
            /** @description Project ID (optional, defaults to user's default project) */
            project_id?: string;
            /**
             * @description Security setting
             * @default true
             */
            secure: boolean;
            /** @description Storage in GB */
            storage_gb?: number;
            /** @description Template name or ID (defaults to "base") */
            template?: string;
            /** @description Timeout in seconds (defaults to 300) */
            timeout?: number;
        };
        CreateTemplateFromSandboxRequest: {
            /** @description CPU count (nil/omit = inherit from base template, 0 = explicitly inherit, >0 = use) */
            cpu_count?: number;
            /** @description Custom startup command */
            custom_command?: string;
            /** @description Template description */
            description?: string;
            /** @description Memory in MB (nil/omit = inherit from base template, 0 = explicitly inherit, >0 = use) */
            memory_mb?: number;
            /** @description Template name (must be unique for the user) */
            name: string;
            /** @description Additional ports as JSON string (added to inherited ports from base template) */
            ports?: string;
            /** @description Custom readiness probe command */
            ready_command?: string;
            /** @description If true, remove unprotected ports from base template */
            reset_ports?: boolean;
            /**
             * @description Template visibility: 'private' (owner only), 'account_shared' (account members), or 'public' (all users). Admin users can create public templates (default: 'public' for admin, 'private' for non-admin)
             *
             * @enum {string}
             */
            visibility?: "private" | "account_shared" | "public";
        };
        Error: {
            /** @description Error code */
            code?: string;
            /** @description Additional error details */
            details?: Record<string, never>;
            /** @description Error message */
            message: string;
        };
        /** @description Locality preferences for sandbox scheduling. Controls where the sandbox
         *     will be scheduled based on geographical preferences. By default, locality
         *     is disabled and the system uses load-balanced scheduling.
         *      */
        LocalityConfig: {
            /**
             * @description Automatically detect the preferred region from the source IP address.
             *     When enabled, the system will infer the region from your IP address using GeoIP.
             *     If detection fails or the detected region is not available, the system will
             *     fall back to default load-balanced scheduling (unless force is true).
             *
             * @default false
             */
            auto_detect: boolean;
            /**
             * @description **Hard constraint**: fail if the requested region is not available.
             *
             *     When force is true and the specified region has no available clusters,
             *     sandbox creation will fail with a 409 Conflict error instead of falling back
             *     to other regions.
             *
             *     **WARNING**: Use this option carefully. If the requested region is unavailable,
             *     sandbox creation will fail even if other regions have capacity. This is a
             *     hard constraint that prioritizes region preference over availability.
             *
             *     **Best practice**: Only use force=true when you have strict compliance or
             *     regulatory requirements. For most use cases, use force=false (default) to
             *     allow graceful fallback to other available regions.
             *
             * @default false
             */
            force: boolean;
            /**
             * @description Explicitly specify a preferred Sandbox Region. When provided, the system
             *     will prefer clusters in this region. If no clusters are available in this
             *     region and force is false, the system will fall back to other available clusters.
             *     Use GET /v1/scalebox-regions to get a list of available regions.
             *
             * @example us-east
             */
            region?: string;
        };
        PortConfig: {
            /**
             * @description Whether port is protected (template ports only, cannot be removed)
             * @default false
             */
            is_protected: boolean;
            /** @description Port name (required, must be DNS-compatible) */
            name: string;
            /**
             * Format: int32
             * @description Container port number
             */
            port: number;
            /**
             * @description Port protocol
             * @default TCP
             * @enum {string}
             */
            protocol: "TCP" | "UDP";
            /**
             * Format: int32
             * @description Kubernetes service port (defaults to port if not provided)
             */
            service_port?: number;
        };
        SandboxDeploymentResponse: {
            /** @description Access token for the sandbox */
            access_token?: string;
            /** @description External access URL */
            access_url?: string;
            /** @description Cluster ID where sandbox is deployed */
            cluster_id?: string;
            /** @description Kubernetes deployment name */
            deployment?: string;
            /**
             * Format: date-time
             * @description Deployment timestamp
             */
            deployment_at?: string;
            /** @description Driver version used for deployment */
            driver_version?: string;
            /** @description Kubernetes ingress name */
            ingress?: string;
            /** @description Internal cluster URL */
            internal_url?: string;
            /** @description Kubernetes namespace */
            namespace?: string;
            /** @description Sandbox ID */
            sandbox_id?: string;
            /** @description Type of sandbox deployed */
            sandbox_type?: string;
            /** @description Kubernetes service name */
            service?: string;
            /** @description Deployment status */
            status?: string;
        };
        SandboxResponse: {
            /**
             * Format: date-time
             * @description When sandbox was allocated to cluster
             */
            allocation_time?: string | null;
            /** @description Internet access setting */
            allow_internet_access?: boolean;
            /** @description Kubernetes cluster ID where sandbox is deployed */
            cluster_id?: string | null;
            /** @description Container name within the pod */
            container_name?: string | null;
            cost?: {
                /**
                 * Format: float
                 * @description Hourly rate for this sandbox
                 */
                hourlyRate?: number;
                /**
                 * Format: float
                 * @description Total cost accumulated
                 */
                totalCost?: number;
            };
            /** @description Number of CPU cores */
            cpu_count?: number;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            created_at?: string;
            /** @description Custom ports added to sandbox */
            custom_ports?: components["schemas"]["PortConfig"][];
            /**
             * @description Whether sandbox deletion is in progress
             * @default false
             */
            deletion_in_progress: boolean;
            /** @description Sandbox description */
            description?: string;
            /**
             * Format: date-time
             * @description When sandbox lifecycle ended
             */
            ended_at?: string | null;
            /** @description Environment variables */
            env_vars?: {
                [key: string]: string;
            };
            /** @description Token for sandbox access */
            envd_access_token?: string | null;
            /** @description Last known Kubernetes pod status */
            last_pod_status?: string | null;
            /** @description Memory in MB */
            memory_mb?: number;
            /** @description Metadata key-value pairs */
            metadata?: {
                [key: string]: string;
            };
            /** @description Sandbox name */
            name?: string;
            /** @description User namespace ID in the cluster */
            namespace_id?: string | null;
            /**
             * @description Network proxy country setting
             * @enum {string|null}
             */
            net_proxy_country?: "united-states" | "canada" | "japan" | "malaysia" | "brazil" | "france" | "italy" | "china" | "hong-kong" | null;
            /** @description Node where pod is scheduled */
            node_name?: string | null;
            owner?: {
                /** @description Display name of the owner */
                display_name?: string | null;
                /** @description Email of the owner */
                email?: string;
                /** @description User ID of the owner */
                user_id?: string;
                /** @description Username of the owner */
                username?: string;
            };
            /** @description Owner user ID */
            owner_user_id?: string;
            /** @description Pod IP address */
            pod_ip?: string | null;
            /** @description Kubernetes pod name */
            pod_name?: string | null;
            /** @description Kubernetes pod UID */
            pod_uid?: string | null;
            /** @description All ports (template ports + custom ports) */
            ports?: components["schemas"]["PortConfig"][];
            /** @description Project ID */
            project_id?: string;
            /** @description Project name */
            project_name?: string;
            /** @description Reason for current status or failure */
            reason?: string;
            resources?: {
                /** @description Bandwidth allocation (placeholder) */
                bandwidth?: number;
                /** @description CPU cores allocated */
                cpu?: number;
                /** @description Memory in MB allocated */
                memory?: number;
                /** @description Storage in GB allocated */
                storage?: number;
            };
            /** @description Sandbox access domain */
            sandbox_domain?: string | null;
            /** @description Unique sandbox identifier */
            sandbox_id?: string;
            /** @description Security setting */
            secure?: boolean;
            /**
             * Format: date-time
             * @description When sandbox started running
             */
            started_at?: string | null;
            /**
             * @description Current sandbox status
             * @enum {string}
             */
            status?: "created" | "starting" | "running" | "terminating" | "terminated" | "failed";
            /**
             * Format: date-time
             * @description When sandbox stopped
             */
            stopped_at?: string | null;
            /** @description Storage in GB */
            storage_gb?: number;
            /**
             * @description Detailed substatus for transitional states
             * @enum {string}
             */
            substatus?: "allocating" | "deploying" | "initializing" | "waiting_ready" | "cleaning_resources" | "cleaning_data";
            /** @description Template ID */
            template_id?: string;
            /** @description Template name */
            template_name?: string;
            /** @description Ports from template */
            template_ports?: components["schemas"]["PortConfig"][];
            /** @description Timeout in seconds */
            timeout?: number;
            /**
             * Format: date-time
             * @description When sandbox will timeout
             */
            timeout_at?: string | null;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at?: string;
            /** @description Uptime in seconds */
            uptime?: number;
        };
        SandboxStatsResponse: {
            /**
             * Format: float
             * @description Average CPU usage percentage
             */
            avg_cpu_usage?: number;
            /**
             * Format: float
             * @description Average memory usage percentage
             */
            avg_memory_usage?: number;
            /** @description Number of failed sandboxes */
            failed_sandboxes?: number;
            /** @description Number of running sandboxes */
            running_sandboxes?: number;
            /** @description Number of terminated sandboxes */
            terminated_sandboxes?: number;
            /**
             * Format: float
             * @description Total cost accumulated
             */
            total_cost?: number;
            /** @description Total number of sandboxes */
            total_sandboxes?: number;
            /**
             * Format: float
             * @description Total uptime in hours
             */
            total_uptime_hours?: number;
        };
        SandboxTimeoutRequest: {
            /** @description New timeout in seconds (must be >= already used lifetime) */
            timeout: number;
        };
        ScaleboxRegion: {
            /**
             * @description Region identifier (e.g., 'us-east', 'eu-west', 'ap-southeast')
             * @example us-east
             */
            id: string;
            /**
             * @description Human-readable region name (e.g., 'US East (N. Virginia)')
             * @example US East (N. Virginia)
             */
            name: string;
        };
        SuccessResponse: {
            data?: Record<string, never>;
            message?: string;
            success?: boolean;
        };
        UpdateSandboxRequest: {
            /** @description New timeout in seconds (must be greater than current timeout) */
            timeout: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
